apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "storage.fullname" . }}-provisioner
  labels:
    {{- include "storage.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "storage.fullname" . }}-provisioner
  labels:
    {{- include "storage.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "persistentvolumeclaims", "configmaps", "pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "storage.fullname" . }}-provisioner
  labels:
    {{- include "storage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "storage.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ include "storage.fullname" . }}-provisioner
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "storage.fullname" . }}-provisioner
  labels:
    {{- include "storage.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "storage.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ include "storage.fullname" . }}-provisioner
    namespace: {{ .Release.Namespace }}

