image:
  repository: rancher/local-path-provisioner
  tag: v0.0.32
  pullPolicy: IfNotPresent

helperPod:
  image:
    repository: rancher/library-busybox
    tag: "1.32.1"
    pullPolicy: IfNotPresent

storageClass:
  name: local-path
  createDefaultClass: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

config:
  defaultPath: /opt/local-path-provisioner

debug: false
