definitions:
  steps:
    - step: &validate
        name: Validate Helm Charts
        runs-on:
          - self.hosted
          - linux.shell
        script:
          - ./scripts/helm.sh deps
          - ./scripts/helm.sh lint
          - ./scripts/helm.sh template
    - step: &deploy
        name: Deploy Homelab
        deployment: production
        runs-on:
          - self.hosted
          - linux.shell
        script:
          - ./scripts/helm.sh deps
          - ./scripts/helm.sh deploy

pipelines:
  pull-requests:
    "**":
      - step: *validate
  branches:
    main:
      - step: *validate
      - step: *deploy
  custom:
    deploy-homelab:
      - step: *validate
      - step: *deploy
