victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack

  external:
    grafana:
      host: https://grafana.renzlab.com
      datasource: VictoriaMetrics

  vmsingle:
    enabled: true
    spec:
      retentionPeriod: 30d
      replicaCount: 1
      storage:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi

  vmagent:
    enabled: true
    spec:
      scrapeInterval: 30s
      externalLabels:
        cluster: renzlab-homelab

  grafana:
    enabled: true
    fullnameOverride: grafana
    initChownData:
      enabled: false
      image:
        registry: docker.io
        repository: rancher/library-busybox
        tag: "1.32.1"
        pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    grafana.ini:
      server:
        domain: grafana.renzlab.com
        root_url: https://grafana.renzlab.com
    ingress:
      enabled: false
      hosts:
        - grafana.renzlab.com
      tls:
        - hosts:
            - grafana.renzlab.com

  defaultDatasources:
    victoriametrics:
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          access: proxy
          isDefault: true

  prometheus-node-exporter:
    enabled: true

  kube-state-metrics:
    enabled: true

  kubelet:
    enabled: true

  kubeApiServer:
    enabled: true

  kubeControllerManager:
    enabled: true

  kubeScheduler:
    enabled: true

  kubeProxy:
    enabled: true

  coreDns:
    enabled: true

  kubeEtcd:
    enabled: true
