victoria-metrics-k8s-stack:
  fullnameOverride: vm-k8s-stack

  external:
    grafana:
      host: https://grafana.renzlab.com
      datasource: VictoriaMetrics

  defaultDashboards:
    enabled: false

  vmsingle:
    enabled: true
    spec:
      retentionPeriod: 30d
      replicaCount: 1
      storage:
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi

  vmagent:
    enabled: true
    spec:
      replicaCount: 1
      scrapeInterval: 30s
      externalLabels:
        cluster: renzlab-homelab

  grafana:
    enabled: true
    fullnameOverride: grafana
    env:
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_FROM_ADDRESS: projectzero2795@gmail.com
      GF_SMTP_FROM_NAME: Renz Beltran
      GF_SMTP_SKIP_VERIFY: "false"
      GF_SMTP_STARTTLS_POLICY: MandatoryStartTLS
    smtp:
      existingSecret: grafana-smtp
    initChownData:
      enabled: false
      image:
        registry: docker.io
        repository: rancher/library-busybox
        tag: "1.32.1"
        pullPolicy: IfNotPresent
    persistence:
      enabled: true
      storageClassName: local-path
      size: 10Gi
    sidecar:
      dashboards:
        enabled: false
    grafana.ini:
      server:
        domain: grafana.renzlab.com
        root_url: https://grafana.renzlab.com
    ingress:
      enabled: false
      hosts:
        - grafana.renzlab.com
      tls:
        - hosts:
            - grafana.renzlab.com

  defaultDatasources:
    victoriametrics:
      datasources:
        - name: VictoriaMetrics
          type: prometheus
          access: proxy
          isDefault: true

  prometheus-node-exporter:
    enabled: true

  kube-state-metrics:
    enabled: true

  kubelet:
    enabled: true

  kubeApiServer:
    enabled: true

  kubeControllerManager:
    enabled: true

  kubeScheduler:
    enabled: true

  kubeProxy:
    enabled: true

  coreDns:
    enabled: true

  kubeEtcd:
    enabled: true
